version: 0.2

phases:
  pre_build:
    commands:
      - ls -la .
      - env
  build:
    commands:
      - aws --version
      - docker run --rm -e SITE_ROOT="${SITE_ROOT}" -e SITE_URL="${SITE_ROOT}/${LANGUAGE}/${VERSION}/" -e VERSION=${VERSION} -e LANGUAGE=${LANGUAGE} -v ${PWD}:/workspace/ -w /workspace/ ghcr.io/consensys/doctools-builder:${DOCTOOLS_IMAGE_VERSION} build -s -d ${OUTPUT_DIR} --config-file ${MKDOCS_CONFIG}
  post_build:
    commands:
      - ls -la .
      - env
      - if [[ "$CODEBUILD_WEBHOOK_EVENT" == "PUSH" ]]; then export SITE_ROOT=fred; fi
      - env
      - aws s3 sync ${OUTPUT_DIR}/ s3://${S3_OUTPUT_BUCKET}/goquorum/${SITE_ROOT}/
