# Copyright 2019 ConsenSys AG.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# Project information
site_name: GoQuorum
site_url: https://docs.goquorum.consensys.net/
site_description: A permissioned implementation of Ethereum supporting data privacy
site_author: GoQuorum community
copyright: GoQuorum and its documentation are licensed under LGPL-3.0 License /
  This <a href="https://readthedocs.org/">Readthedocs.org</a> documentation is maintained with love by <a href="https://consensys.net/">Consensys</a>.

#extra project info and template customisation
extra:
  latest_version_warning:
    url_contains: /latest/
    text: 'You are reading GoQuorum development version documentation and
    some displayed features may not be available in the stable release.
    You can switch to stable version using the version box at screen bottom.'
  support:
    gitter: https://gitter.im/PegaSysEng/GoQuorum
    email: support@pegasys.tech
    pegasys_website: https://consensys.net/
    issues: https://github.com/PegaSysEng/doc.goquorum/issues
  google:
    site_verification: 'TODO'
    tag_manager: 'TODO'


# Software Repository
repo_name: PegaSysEng/GoQuorum
repo_url: https://github.com/PegaSysEng/GoQuorum

theme:
  name: material
  custom_dir: common/custom_theme
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: 'en'
  logo: 'images/logo.png'
  favicon: 'images/logo-48x48.png'

extra_css:
  - 'theme/assets/stylesheets/extra.css'

nav:
  - How to:
      - Get started:
          - Overview: HowTo/GetStarted/GettingStartedOverview.md
          - Install: HowTo/GetStarted/Install.md
          - With Cakeshop: HowTo/GetStarted/Cakeshop.md
          - Upgrade to 2.6.0: HowTo/GetStarted/migration.md
          - With GoQuorum Wizard:
              - Get started: HowTo/GetStarted/Wizard/GettingStarted.md
              - Interacting: HowTo/GetStarted/Wizard/Interacting.md
      - Configure:
          - Genesis file: HowTo/Configure/GenesisOptions.md
          - High availability: HowTo/Configure/HighAvailability.md
          - Permissions:
              - Basic permissions: HowTo/Configure/BasicPermissions.md
              - Enhanced permissions: HowTo/Configure/EnhancedPermissions.md
          - Plugins: HowTo/Configure/Plugins.md
          - DNS: HowTo/Configure/dns.md
      - Develop plugins: HowTo/DevelopPlugins.md
      - Manage keys:
          - Overview: HowTo/ManageKeys/ManagingKeys.md
          - Using clef: HowTo/ManageKeys/clef.md
          - Using account plugins: HowTo/ManageKeys/AccountPlugins.md
      - Use:
          - Adding nodes to network: HowTo/Use/adding_nodes.md
          - Adding nodes examples: HowTo/Use/add_node_examples.md
          - Adding IBFT validators: HowTo/Use/AddingIBFTValidators.md
          - JSON-RPC API security: HowTo/Use/JSON-RPC-API-Security.md
          - Enhanced permissions: HowTo/Use/EnhancedPermissions.md
          - Smart contracts: HowTo/Use/DevelopingSmartContracts.md
          - GraphQL: HowTo/Use/graphql.md
          - Backup and restore: HowTo/Use/import-export.md
  - Tutorials:
      - Create network from scratch: Tutorials/Creating-A-Network-From-Scratch.md
      - Create permissioned network: Tutorials/CreatePermissionedNetwork.md
  - Concepts:
      - ConsenSys Quorum: Concepts/ConsenSysQuorum.md
      - Architecture: Concepts/Architecture.md
      - Account management: Concepts/AccountManagement.md
      - Privacy:
          - Overview: Concepts/Privacy/Privacy.md
          - Public and private transactions: Concepts/Privacy/PrivateAndPublic.md
          - Private transaction manager: Concepts/Privacy/PrivateTransactionManager.md
          - Private transaction lifecycle: Concepts/Privacy/PrivateTransactionLifecycle.md
          - Contract extension: Concepts/Privacy/ContractExtension.md
      - Consensus:
          - Overview: Concepts/Consensus/Overview.md
          - IBFT: Concepts/Consensus/IBFT.md
          - Raft: Concepts/Consensus/Raft.md
      - Permissioning:
          - Overview: Concepts/Permissioning/PermissionsOverview.md
          - Basic permissions: Concepts/Permissioning/BasicNetworkPermissions.md
          - Enhanced:
              - Overview: Concepts/Permissioning/Enhanced/EnhancedPermissionsOverview.md
              - Contract design: Concepts/Permissioning/Enhanced/ContractDesign.md
      - Plugins:
          - Overview: Concepts/Plugins/Plugins.md
          - Architecture: Concepts/Plugins/PluginsArchitecture.md
      - Security Framework:
          - Overview: Concepts/Security/Framework/Overview.md
          - GoQuorum Network:
            - Consortium: Concepts/Security/Framework/GoQuorumNetworkSecurity/Consortium.md
            - GoQuorum Node: Concepts/Security/Framework/GoQuorumNetworkSecurity/Node.md
            - Transaction Manager: Concepts/Security/Framework/GoQuorumNetworkSecurity/TransactionManager.md
            - Operational Considerations: Concepts/Security/Framework/GoQuorumNetworkSecurity/OpertionalConsiderations.md
          - Decentralized App:
            - Frontend: Concepts/Security/Framework/DecentralizedApplication/FrontendComponents.md
            - Smart Contracts: Concepts/Security/Framework/DecentralizedApplication/SmartContractsSecurity.md
      - Network and chain ID: Concepts/NetworkAndChainID.md
      - Cakeshop: Concepts/Cakeshop.md
  - Reference:
      - API:
          - Privacy: Reference/APIs/PrivacyAPI.md
          - Permissions: Reference/APIs/PermissioningAPIs.md
          - Contract extension: Reference/APIs/ContractExtensionAPIs.md
      - Example genesis file: Reference/genesis.md
      - Consensus:
          - IBFT Parameters: Reference/Consensus/IBFTParameters.md
          - IBFT RPC API: Reference/Consensus/IBFT-RPC-API.md
          - Raft RPC API: Reference/Consensus/Raft-RPC-API.md
      - Plugins:
          - Initialization interface: Reference/Plugins/init_interface.md
          - helloworld:
              - Interface: Reference/Plugins/helloworld/interface.md
              - Implementation: Reference/Plugins/helloworld/implementation.md
          - account:
            - Developers: Reference/Plugins/account/For-Developers.md
            - Users: Reference/Plugins/account/For-Users.md
            - Interface: Reference/Plugins/account/interface.md
          - security:
            - Interface: Reference/Plugins/security/interface.md
            - Implementation: Reference/Plugins/security/implementation.md
      - GoQuorum projects: Reference/GoQuorum-Projects.md
      - Remix plugin:
          - Overview: Reference/RemixPlugin/Overview.md
          - Getting started: Reference/RemixPlugin/GettingStarted.md
      - quorum.js:
          - Overview: Reference/quorum.js/Overview.md
          - extend API: Reference/quorum.js/extend.md
          - RawTransactionManager API: Reference/quorum.js/RawTransactionManager.md
      - FAQ: Reference/FAQ.md
      - Cakeshop FAQ: Reference/CakeshopFAQ.md

markdown_extensions:
  - toc:
      permalink: 
      toc_depth: 3
  - codehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - markdown_include.include:
      base_path: docs
  - admonition
  - footnotes
  - def_list
  - abbr
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta
  - smarty
  - attr_list
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml

plugins:
  - search:
      lang: 'en'
      separator: '[\s]+'
  - markdownextradata
  - redirects:
      redirect_maps:
        # Configure redirects using key:value pairs:
        # old_path.md: new_path.md
        # you can't use an already redirected path as an old_path.
        # new_path can be a file inside the docs/ folder or any URL (http://...)
        Account-Key-Management/Overview.md: Concepts/AccountManagement.md
        Account-Key-Management/Quorum/Clef.md: HowTo/ManageKeys/clef.md
        Account-Key-Management/Quorum/Keystore-Files.md: HowTo/ManageKeys/ManagingKeys.md
        Account-Key-Management/Quorum/Overview.md: Concepts/AccountManagement.md
        Account-Key-Management/Quorum/account-Plugins/Overview.md: HowTo/ManageKeys/AccountPlugins.md
        Account-Key-Management/Tessera/Overview.md: Concepts/AccountManagement.md
        Consensus/ibft/ibft.md: Concepts/Consensus/IBFT.md
        Consensus/Consensus.md: Concepts/Consensus/Overview.md
        Consensus/raft/raft.md: Concepts/Consensus/Raft.md
        Getting Started/permissioned-nodes.md: HowTo/Configure/BasicPermissions.md
        Getting Started/running.md: HowTo/GetStarted/GettingStartedOverview.md
        Consensus/ibft/ibft-parameters.md: Reference/Consensus/IBFTParameters.md
        Consensus/ibft/istanbul-rpc-api.md: Reference/Consensus/IBFT-RPC-API.md
        Consensus/raft/raft-rpc-api.md: Reference/Consensus/Raft-RPC-API.md
        Permissioning/Basic NetworkPermissions.md: Concepts/Permissioning/BasicNetworkPermissions.md
        Permissioning/Enhanced Permissions Model/Contract Design.md: Concepts/Permissioning/Enhanced/ContractDesign.md
        Permissioning/Permissions Overview.md: Concepts/Permissioning/PermissionsOverview.md
        PluggableArchitecture/Overview.md: Concepts/Plugins/Plugins.md
        PluggableArchitecture/Internals.md: Concepts/Plugins/PluginsArchitecture.md
        Privacy/Contract-Extension/Overview.md: Concepts/Privacy/ContractExtension.md
        Privacy/Overview.md: Concepts/Privacy/PrivateAndPublic.md
        Privacy/Lifecycle-of-a-private-transaction.md: Concepts/Privacy/PrivateTransactionLifecycle.md
        Privacy/Privacy-Manager.md: Concepts/Privacy/PrivateTransactionManager.md
        Security/Framework/Decentralized Application/Frontend Components.md: Concepts/Security/Framework/DecentralizedApplication/FrontendComponents.md
        Security/Framework/Decentralized Application/Smart Contracts Security.md: Concepts/Security/Framework/DecentralizedApplication/SmartContractsSecurity.md
        Security/Framework/Quorum Network Security/Consortium.md: Concepts/Security/Framework/GoQuorumNetworkSecurity/Consortium.md
        Security/Framework/Quorum Network Security/Node.md: Concepts/Security/Framework/GoQuorumNetworkSecurity/Node.md
        Security/Framework/Quorum Network Security/Opertional Considerations.md: Concepts/Security/Framework/GoQuorumNetworkSecurity/OpertionalConsiderations.md
        Security/Framework/Quorum Network Security/Transaction Manager.md: Concepts/Security/Framework/GoQuorumNetworkSecurity/TransactionManager.md
        Security/Framework/Overview.md: Concepts/Security/Framework/Overview.md
        How-To-Guides/HA_Setup.md: HowTo/Configure/HighAvailability.md
        How-To-Guides/add_ibft_validator.md: HowTo/Use/AddingIBFTValidators.md
        Permissioning/Enhanced Permissions Model/setup.md: HowTo/Configure/EnhancedPermissions.md
        Quorum Features/dns.md: HowTo/Configure/dns.md
        PluggableArchitecture/PluginDevelopment.md: HowTo/DevelopPlugins.md
        Cakeshop/Getting started.md: HowTo/GetStarted/Cakeshop.md
        Getting Started/Getting Started Overview.md: HowTo/GetStarted/GettingStartedOverview.md
        Getting Started/Installing.md: HowTo/GetStarted/Install.md
        Wizard/GettingStarted.md: HowTo/GetStarted/Wizard/GettingStarted.md
        Wizard/Interacting.md: HowTo/GetStarted/Wizard/Interacting.md
        Getting Started/migration.md: HowTo/GetStarted/migration.md
        Permissioning/Enhanced Permissions Model/Usage.md: HowTo/Use/EnhancedPermissions.md
        Quorum Features/rpc-security.md: HowTo/Use/JSON-RPC-API-Security.md
        How-To-Guides/add_node_examples.md: HowTo/Use/add_node_examples.md
        How-To-Guides/adding_nodes.md: HowTo/Use/adding_nodes.md
        Getting Started/graphql.md: HowTo/Use/graphql.md
        How-To-Guides/import-export.md: HowTo/Use/import-export.md
        Privacy/Contract-Extension/ContractExtension apis.md: Reference/APIs/ContractExtensionAPIs.md
        Permissioning/Enhanced Permissions Model/Permissioning apis.md: Reference/APIs/PermissioningAPIs.md
        Getting Started/api.md: Reference/APIs/PrivacyAPI.md
        Cakeshop/Cakeshop FAQ.md: Reference/CakeshopFAQ.md
        FAQ.md: Reference/FAQ.md
        Getting Started/Quorum-Examples.md: Reference/GoQuorum-Projects.md
        PluggableArchitecture/Plugins/account/For-Developers.md: Reference/Plugins/account/For-Developers.md
        PluggableArchitecture/Plugins/account/For-Users.md: Reference/Plugins/account/For-Users.md
        PluggableArchitecture/Plugins/account/interface.md: Reference/Plugins/account/interface.md
        PluggableArchitecture/Plugins/helloworld/implementation.md: Reference/Plugins/helloworld/implementation.md
        PluggableArchitecture/Plugins/helloworld/interface.md: Reference/Plugins/helloworld/interface.md
        PluggableArchitecture/Plugins/init_interface.md: Reference/Plugins/init_interface.md
        PluggableArchitecture/Plugins/security/implementation.md: Reference/Plugins/security/implementation.md
        PluggableArchitecture/Plugins/security/interface.md: Reference/Plugins/security/interface.md
        RemixPlugin/GettingStarted.md: Reference/RemixPlugin/GettingStarted.md
        RemixPlugin/Overview.md: Reference/RemixPlugin/Overview.md
        Getting Started/genesis.md: Reference/genesis.md
        quorum.js/Overview.md: Reference/quorum.js/Overview.md
        quorum.js/RawTransactionManager.md: Reference/quorum.js/RawTransactionManager.md
        quorum.js/extend.md: Reference/quorum.js/extend.md
        Getting Started/Creating-A-Network-From-Scratch.md: Tutorials/Creating-A-Network-From-Scratch.md
