version: 0.2

phases:
  pre_build:
    commands:
      - ls -la .
      - env
  build:
    commands:
      - aws --version
      - docker run --rm -e SITE_ROOT="${SITE_ROOT}" -e SITE_URL="${SITE_ROOT}/${LANGUAGE}/${VERSION}/" -e VERSION=${VERSION} -e LANGUAGE=${LANGUAGE} -v ${PWD}:/workspace/ -w /workspace/ ghcr.io/consensys/doctools-builder:${DOCTOOLS_IMAGE_VERSION} build -s -d ${OUTPUT_DIR} --config-file ${MKDOCS_CONFIG}
  post_build:
    commands:
      - ls -la .
      - env
      - aws s3 sync ${OUTPUT_DIR}/ s3://${S3_DOCS_BUCKET}/goquorum/${SITE_ROOT}/
      # if a PR then create a /PR-123 link for preview
      # TODO: add the lifecycle rule here
      - |
        if [ "$CODEBUILD_WEBHOOK_EVENT" != "PUSH" ] ; then
          aws s3 sync ${OUTPUT_DIR}/ s3://${S3_DOCS_BUCKET}/goquorum/latest/
        fi  
      # also do latest for main branch ?
      - |
        if [ "$CODEBUILD_WEBHOOK_EVENT" = "PUSH" ] ; then
          aws s3 sync ${OUTPUT_DIR}/ s3://${S3_DOCS_BUCKET}/goquorum/latest/
        fi  