---
name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # the enviroment to deploy to / use secrets from
    environment: no-secret
    # modify the default permissions of the GITHUB_TOKEN, so as to only allow least priveleges
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: ConsenSys/docs-gha/build@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
