---
name: Lint codebase

on: [push, pull_request]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint code
        uses: ConsenSys/doctools.action-builder/actions/tests/lint@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

