---
name: Delete PR preview

on:
  pull_request_target:
    types: [closed]

jobs:
  deploy:
    name: Remove PR preview from pages
    runs-on: ubuntu-latest
    if: ${{github.event.repository.public}} #github pages are always public, not to use for private repos.
    steps:
      - name: 'checkout code from repos'
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Checkout actions
        uses: actions/checkout@v2
        with:
          path: actions

      - name: Delete PR preview
        uses: ConsenSys/doctools.action-builder/actions/pr_preview_delete@main
