---
name: Publish release doc site

on:
  release:
    types: [published]
    branches: [main]

jobs:
  deploy:
    name: Build and publish released site
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
    # secrets are not usable from outside ConsenSys org
    # The workflow will then be disabled for non ConsenSys repositories to prevent useless failure.
    if: github.event.repository.fork == false && github.repository_owner == 'ConsenSys'
    steps:
      - name: checkout code from repos
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required for mkdocs to be able to display pages last update info

      - name: Publish release version to AWS
        uses: ConsenSys/doctools.action-builder/actions/release-publish@main
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SITE_ROOT: ${{ secrets.SITE_ROOT }} # must point at project level. No lang. No version.
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          PROJECT: ${{ secrets.PROJECT }}
          LANGUAGE: 'en'
