---
name: Test spelling and guidelines

# TODO configure and move to common actions

on:
  push:
    branches: [testCI]

jobs:
  spelling:
    name: Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create style dir
        run: |
          mkdir .github/styles
        shell: sh
      - name: Vale
        uses: errata-ai/vale-action@v1.4.0
        with:
          # Optional
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip

          # Optional
          config: https://raw.githubusercontent.com/errata-ai/vale/master/.vale.ini

          # Optional
          files: docs
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
